workflows:
  android-build:
    name: Build APK
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.taxidar"
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
